### ISSUE TITLE
Not reading RAZZLE vars in production mode.

### ISSUE THREAD

**Issue by giuliaghisini** [eea/volto-matomo#11]
In production mode (using build) razzle variables are not loaded. 

I think the problem is that them are readed from window.env instead process.env
it should be
process.env?.RAZZLE_MATOMO_SITE_ID 
proveces.env?.RAZZLE_MATOMO_URL

**Comment by danielamormocea** [comment]
Hi @giuliaghisini 

I tested it and it works fine on my side and on demo (so also on prod). If the problem persists at you, I'd ask you to kindly write all the steps so we can also reproduce it. Thanks!
