### ISSUE TITLE
url_params on a page track view appear not to be sent to Matomo

### ISSUE THREAD

**Issue by fredvd** [eea/volto-matomo#34]
Filing this issue also on behalf of @ericof because I chatted with him about this. 

We've been trying to run some campaigns on the plone.org website, where we link from a twitter/mastodon post to an article on plone.org with url parameters. A link for example would be like this:

`https://plone.org/news-and-events/news/2023/plone-6-0-6-released?mtm_campaign=releases&mtm_medium=social`

The idea is that matomo picks up the url parameters and counts one hit to the releases campaign for the social media medium. However: Matomo never records this 'hit' .  We suspect that volto-matomo in the AppExtra component that gets configured only pushes the href but strips of any url params here: 

https://github.com/eea/volto-matomo/blob/4a62439b4a1aaf6287b4ce0475ab259916edcdee/src/MatomoAppExtra.jsx#L12-L25

**Comment by ericof** [comment]
@avoinea, @nileshgulia1  this is quite important to the Plone Foundation :-) Could you prioritize it, please?

**Comment by nileshgulia1** [comment]
Alin is on holiday. I will look into this.

**Comment by ericof** [comment]
@nileshgulia1 Thank you! It would help us a lot if you are able to fix this

**Comment by fredvd** [comment]
Should have been fixed in PR #35 last year already. Closing this issue
