### ISSUE TITLE
release policy?

### ISSUE THREAD

**Issue by ksuess** [eea/volto-matomo#7]
I wonder how releases are done here. https://github.com/eea/volto-matomo/pull/5 is merged to branch 'develop' 6 days ago. May I have some info how the process of merging and releasing is?

**Comment by nileshgulia1** [comment]
Hi @ksuess ,
The PRs should be made directly to develop branch, we do not encourage PRs directly to master. Recently @valentinab25 developed  an auto-release pipeline which will trigger a minor release as soon as a PR lands in master.

**Comment by ksuess** [comment]
Yes, thats obvious: PRs to branch develop.
And what's about the merge to develop to master/main?

**Comment by nileshgulia1** [comment]
We can merge develop to master/main on regular basis after an approving review, and thus cutting a release. 
So we can generally use "develop" for committing directly for small features. And sub branches( on top of develop) for major features.

**Comment by ksuess** [comment]
So this https://github.com/eea/volto-matomo/pull/5 is approved and merged in develop. Would you do a release?

**Comment by tiberiuichim** [comment]
@ksuess Sometimes it's easy to get PRs lost "in the inbox", and I, for example, don't watch all the volto addon repos for PRs. Mention one of us, to be sure we get the notifications.

**Comment by nileshgulia1** [comment]
@ksuess The pR landed in master now. It will be released to npm. Thanks.

**Comment by ksuess** [comment]
Thank you @nileshgulia1 and @tiberiuichim !
